apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-crud-deployment
  namespace: phpsite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-crud-app
  template:
    metadata:
      labels:
        app: php-crud-app
    spec:
      containers:
      - name: php-crud
        image: thiagomartinsemartins/php_crud
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
        - name: php-crud-data
          mountPath: /data/
      volumes:
      - name: php-crud-data
        persistentVolumeClaim:
          claimName: php-crud-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: php-crud-service
  namespace: phpsite
spec:
  selector:
    app: php-crud-app
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  namespace: phpsite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-app
  template:
    metadata:
      labels:
        app: database-app
    spec:
      containers:
      - name: database
        image: thiagomartinsemartins/bancodedados_sql
        ports:
        - containerPort: 3306
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
        - name: database-data
          mountPath: /var/lib/mysql
      volumes:
      - name: database-data
        persistentVolumeClaim:
          claimName: database-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: phpsite
spec:
  selector:
    app: database-app
  ports:
  - name: mysqlS
    port: 3306
    targetPort: 3306
  type: NodePort

